version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: ahmedmansy/live:1.0.0
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
    volumes:
      - ./Pr:/app/Pr
      - ./uploads:/app/uploads

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile # Path to your frontend Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./my-app:/app # Assuming your frontend code is inside the my-app folder

volumes:
  pgdata: {}
